name: test
on:
  workflow_dispatch:
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Run 
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: notify
        if: always()
        uses: cinotify/github-action@main
        with:
          to: 'utkarshamendhe7@gmail.com'
          subject: 'github workflow'
          body: '<em>This is a notification from GitHub actions.</em>'
          type: 'text/html'
          # attachment: 'artifacts.zip'
