name: test
on:
  workflow_dispatch:
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Run 
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          Add other actions to build,
          echo test, and deploy your project.
